### ISSUE TITLE
[Feature]: Ability to create a Custom URL

### ISSUE THREAD

**Issue by DraganRatkovich** [nvdaes/urlShortener#8]
### Problem

Missing feature: setting the URL name when shortening the URL

### Suggestion

Hello,

@nvdaes As you may already know, is.gd allows to create your own customised URL when shortening a URL, making it easy to remember the shortened URL if the shortened link refers to some information, social media link, or video, for example YouTube content, etc.

My question is, is it possible to add a checkbox to the addon that will enable or disable custom url creation and if checked, will open an name field to enter a custom name for the url, like is.gd/mycustomurl.

**Comment by nvdaes** [comment]
Hello: do you want to create a custom url in addition to the display name, as far as I"m understanding. If so, this is possible, though if the url chosen is already assigned, this will produce an error and you will need to try it. I"ll look at this to add the requested feature. I prefer to release add-ons with just a minimal set of features for simplicity, and then try to add things according to requests or if something is needed. This may take some time. ThanksEnviado desde mi iPhoneEl 17 abr 2023, a las 21:26, DraganRatkovich ***@***.***> escribió:﻿
Problem
Missing feature: setting the URL name when shortening the URL
Suggestion
Hello,
@nvdaes As you may already know, is.gd allows to create your own customised URL when shortening a URL, making it easy to remember the shortened URL if the shortened link refers to some information, social media link, or video, for example YouTube content, etc.
My question is, is it possible to add a checkbox to the addon that will enable or disable custom url creation and if checked, will open an name field to enter a custom name for the url, like is.gd/mycustomurl.
Alternatives
No response
Additional context
No response

**Comment by DraganRatkovich** [comment]
Hello,

@nvdaes The custom url is also referred to as the display name, I guess, because it is added after is.gd and the slash, for example, the random url looks like this:
https://is.gd/jfwT2j
and the custom url looks like this:
https://is.gd/myurl.

In the is.gd website, there is one clickable after the edit field where you need to enter the URL to shorten, and it's called "Further options/custom URL." Clicking on this interactive element brings up an edit box where you need to enter a custom URL ending as I mentioned above.

Hope that helps.

**Comment by nvdaes** [comment]
Ok. The display name mentioned by me is the name presented in the list of shortened URLs, in NVDA gui. I"ll work on an edit box to enter a custom URL. This will be optional, so I think that a checkbox is not needed.Enviado desde mi iPhoneEl 18 abr 2023, a las 8:43, DraganRatkovich ***@***.***> escribió:﻿
Hello,
@nvdaes The custom url is also referred to as the display name, I guess, because it is added after is.gd and the slash, for example, the random url looks like this:
https://is.gd/jfwT2j
and the custom url looks like this:
https://is.gd/myurl.
In the is.gd website, there is one clickable after the edit field where you need to enter the URL to shorten, and it's called "Further options/custom URL." Clicking on this interactive element brings up an edit box where you need to enter a custom URL ending as I mentioned above.
Hope that helps.

**Comment by nvdaes** [comment]
I'm going to release version 2.0.0 (stable). Please get it from the
addons website at https://addons.nvda-project.org in a few minutes.
I'll publish it on the datastore repo:
https://github.com/nvaccess/addon-datastore

This repo is used to provide links for the website, in replacement of
the old addonFiles repository.
Hope this helps.

2023-04-19 10:46 GMT+02:00, Noelia Ruiz Martínez ***@***.***>:

**Comment by DraganRatkovich** [comment]
Hello,

@nvdaes Everything works very well. Thanks for your work.

**Comment by nvdaes** [comment]
Thank you for testing. Let me know if you find any bug please.
Cheers.

2023-04-19 11:21 GMT+02:00, DraganRatkovich ***@***.***>:

**Comment by DraganRatkovich** [comment]
Hello,

@nvdaes I tried to add localization, but when I add the localization file and switch the NVDA language, the add-on interface remains in English.

**Comment by nvdaes** [comment]
The add-on has been registered in the general translation system.
please wait some days and I'll release another stable version with
translations, and then we will be able to check this again.

2023-04-19 17:34 GMT+02:00, DraganRatkovich ***@***.***>:

**Comment by DraganRatkovich** [comment]
@nvdaes At the moment, I only see documentation files in the translation system. I checked the settings file for the desired localization, however it seems that urlShortener is still not registered there in order to localize the interface for the add-on.

**Comment by nvdaes** [comment]
Let"s wait some days.Enviado desde mi iPhoneEl 19 abr 2023, a las 19:29, DraganRatkovich ***@***.***> escribió:﻿
@nvdaes At the moment, I only see documentation files in the translation system. I checked the settings file for the desired localization, however it seems that urlShortener is still not registered there in order to localize the interface for the add-on.

**Comment by nvdaes** [comment]
Ah, I understand after looking at mrconfig repo. I'll report this to
Sean (NV Access).
Thanks for your suggestions!

2023-04-19 19:52 GMT+02:00, Noelia Ruiz Martínez ***@***.***>:
